version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: packaging-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: packaging-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
